### ISSUE TITLE
tiny-dfr crashes for some reason (Error: 13, PermissionDenied)

### ISSUE THREAD

**Issue by angelobdev** [WhatAmISupposedToPutHere/tiny-dfr#37]
Environment: (neofetch)
```
             .',;::::;,'.                angelo@angelombp
         .';:cccccccccccc:;,.            ----------------
      .;cccccccccccccccccccccc;.         OS: Fedora Linux 39 (Workstation Edition) x86_64
    .:cccccccccccccccccccccccccc:.       Host: MacBookPro15,1 1.0
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Kernel: 6.7.7-200.t2.fc39.x86_64
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Uptime: 16 mins
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Packages: 1929 (rpm), 18 (flatpak)
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Shell: zsh 5.9
:cccccccccccccc;MMM.;cccccccccccccccc:   Resolution: 60x2170
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   DE: GNOME 45.5
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM: Mutter
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   WM Theme: Adwaita
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Theme: Adwaita [GTK2/3]
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Icons: Reversal [GTK2/3]
cccccc;dNMWXXXWM0::cccccccccccccc:,      Terminal: alacritty
cccccccc;.:odl:.;cccccccccccccc:,.       CPU: Intel i9-9880H (16) @ 4.800GHz
:cccccccccccccccccccccccccccc:'.         GPU: AMD ATI Radeon RX 460/560D / Pro 450/455/460/555/555X/560/560X
.:cccccccccccccccccccccc:;,..            Memory: 3165MiB / 15882MiB
  '::cccccccccccccc::;,.
```

Journal:

```
Mar 23 13:00:19 angelombp systemd[1]: Started tiny-dfr.service - Tiny Apple silicon touch bar daemon.
░░ Subject: A start job for unit tiny-dfr.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ A start job for unit tiny-dfr.service has finished successfully.
░░
░░ The job identifier is 5706.
Mar 23 13:00:19 angelombp tiny-dfr[5988]: thread 'main' panicked at src/main.rs:410:48:
Mar 23 13:00:19 angelombp tiny-dfr[5988]: called `Result::unwrap()` on an `Err` value: ENOENT
Mar 23 13:00:19 angelombp tiny-dfr[5988]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```
Full stacktrace error:

```
thread 'main' panicked at src/display.rs:31:33:
called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
stack backtrace:
   0:     0x562d312ccec6 - <unknown>
   1:     0x562d312f45f0 - <unknown>
   2:     0x562d312cac5d - <unknown>
   3:     0x562d312ccca4 - <unknown>
   4:     0x562d312ce577 - <unknown>
   5:     0x562d312ce2d9 - <unknown>
   6:     0x562d312cea08 - <unknown>
   7:     0x562d312ce8e2 - <unknown>
   8:     0x562d312cd3c6 - <unknown>
   9:     0x562d312ce640 - <unknown>
  10:     0x562d3105b985 - <unknown>
  11:     0x562d3105bed3 - <unknown>
  12:     0x562d310857d5 - <unknown>
  13:     0x562d31066b26 - <unknown>
  14:     0x562d31066b3c - <unknown>
  15:     0x562d312c44a1 - <unknown>
  16:     0x562d3108c1a7 - <unknown>
  17:     0x7ffbd1a7c14a - __libc_start_call_main
  18:     0x7ffbd1a7c20b - __libc_start_main_impl
  19:     0x562d3105c195 - <unknown>
  20:                0x0 - <unknown>
```

UPDATE: 
I tried to build it myself, this is the error I get:

```
thread 'main' panicked at src/backlight.rs:62:40:
called `Result::unwrap()` on an `Err` value: No Touch Bar backlight device found
stack backtrace:
   0:     0x55bf5f649bb6 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9c4bd387f9f3f544
   1:     0x55bf5f66fee0 - core::fmt::write::h938c332fdab924eb
   2:     0x55bf5f6476ef - std::io::Write::write_fmt::h4a694b02e44e6363
   3:     0x55bf5f649994 - std::sys_common::backtrace::print::ha888e6736b0bc71f
   4:     0x55bf5f64b067 - std::panicking::default_hook::{{closure}}::he19a7f79f7beab5e
   5:     0x55bf5f64adc9 - std::panicking::default_hook::h67efe04e9a5d446e
   6:     0x55bf5f64b4f8 - std::panicking::rust_panic_with_hook::h49021cdbc4b22349
   7:     0x55bf5f64b3d2 - std::panicking::begin_panic_handler::{{closure}}::hfbf601f3d8c62d13
   8:     0x55bf5f64a0b6 - std::sys_common::backtrace::__rust_end_short_backtrace::h98dd020b6e913806
   9:     0x55bf5f64b124 - rust_begin_unwind
  10:     0x55bf5f3aa825 - core::panicking::panic_fmt::h0d3f1893e38be419
  11:     0x55bf5f3aad73 - core::result::unwrap_failed::h1356562ef8bc898c
  12:     0x55bf5f3d3e01 - tiny_dfr::backlight::BacklightManager::new::h3b38aa2c60b3cf17
  13:     0x55bf5f3b94db - tiny_dfr::real_main::h606a987d8acbd219
  14:     0x55bf5f3b8e7d - tiny_dfr::main::h5391a89cfbb22ba8
  15:     0x55bf5f3d4bb3 - std::sys_common::backtrace::__rust_begin_short_backtrace::he3d67ab476317088
  16:     0x55bf5f3db2a9 - std::rt::lang_start::{{closure}}::he35fdcdc61b5acdc
  17:     0x55bf5f643531 - std::rt::lang_start_internal::hc3f700406209db2c
  18:     0x55bf5f3bb7f5 - main
  19:     0x7fc02db9f14a - __libc_start_call_main
  20:     0x7fc02db9f20b - __libc_start_main_impl
  21:     0x55bf5f3ab075 - _start
  22:                0x0 - <unknown>
```

**Comment by kalvinarts** [comment]
I have the same problem. This is the temporary way to fix it: 

```bash
sudo dnf downgrade rust-tiny-dfr
```

This is my system

```
         .';:cccccccccccc:;,.            ----------------------- 
      .;cccccccccccccccccccccc;.         OS: Fedora Linux 39 (Workstation Edition) x86_64 
    .:cccccccccccccccccccccccccc:.       Host: MacBookPro15,2 1.0 
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Kernel: 6.6.3-200.t2.fc39.x86_64 
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Uptime: 14 hours, 41 mins 
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Packages: 2552 (rpm), 20 (flatpak) 
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Shell: zsh 5.9 
:cccccccccccccc;MMM.;cccccccccccccccc:   Resolution: 60x2170 
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   DE: GNOME 45.5 
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM: Mutter 
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   WM Theme: Adwaita 
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Theme: Adwaita [GTK2/3] 
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Icons: Adwaita [GTK2/3] 
cccccc;dNMWXXXWM0::cccccccccccccc:,      Terminal: tilix 
cccccccc;.:odl:.;cccccccccccccc:,.       CPU: Intel i5-8279U (8) @ 4.100GHz 
:cccccccccccccccccccccccccccc:'.         GPU: Intel CoffeeLake-U GT3e [Iris Plus Graphics 655] 
.:cccccccccccccccccccccc:;,..            Memory: 10254MiB / 15836MiB 
  '::cccccccccccccc::;,.
```
